// ============================================================================
// RDP-CRYPTO: Stealth Address Implementation
// ============================================================================
//
// Implements Dual-Key Stealth Address Protocol (DKSAP):
// - Receiver has spend key (a, A) and view key (b, B)
// - Sender generates one-time stealth address using receiver's public keys
// - Only receiver can detect and spend funds sent to stealth address
//
// Reference: https://eprint.iacr.org/2014/763.pdf
// ============================================================================

use crate::scalar::Scalar;
use crate::point::Point;

use crate::types::{CryptoResult, SCALAR_SIZE, POINT_SIZE};

#[cfg(feature = "std")]
use rand_core::{RngCore, CryptoRng};

/// Domain separation for stealth address derivation
const DOMAIN_STEALTH_SHARED_SECRET: &[u8] = b"RDP_STEALTH_SHARED_SECRET_V1";

// ============================================================================
// Types
// ============================================================================

/// Stealth Meta Address - published by receiver
/// Contains spend public key (A) and view public key (B)
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StealthMetaAddress {
    /// Spend public key: A = a*G
    pub spend_pubkey: [u8; POINT_SIZE],
    /// View public key: B = b*G  
    pub view_pubkey: [u8; POINT_SIZE],
}

/// Stealth Address Output - generated by sender
/// Contains the one-time stealth address and ephemeral pubkey
#[derive(Clone, Copy, Debug)]
pub struct StealthAddressOutput {
    /// One-time stealth public key (destination)
    pub stealth_pubkey: [u8; POINT_SIZE],
    /// Ephemeral public key R = r*G (must be published for receiver to scan)
    pub ephemeral_pubkey: [u8; POINT_SIZE],
}

/// Stealth Key Pair - receiver's full key material
#[derive(Clone)]
pub struct StealthKeyPair {
    /// Spend secret key: a
    pub spend_secret: [u8; SCALAR_SIZE],
    /// Spend public key: A = a*G
    pub spend_pubkey: [u8; POINT_SIZE],
    /// View secret key: b
    pub view_secret: [u8; SCALAR_SIZE],
    /// View public key: B = b*G
    pub view_pubkey: [u8; POINT_SIZE],
}

// ============================================================================
// Implementation
// ============================================================================

impl StealthMetaAddress {
    /// Create from raw bytes
    pub fn new(spend_pubkey: [u8; POINT_SIZE], view_pubkey: [u8; POINT_SIZE]) -> Self {
        Self {
            spend_pubkey,
            view_pubkey,
        }
    }

    /// Serialize to bytes (64 bytes total)
    pub fn to_bytes(&self) -> [u8; 64] {
        let mut bytes = [0u8; 64];
        bytes[..32].copy_from_slice(&self.spend_pubkey);
        bytes[32..].copy_from_slice(&self.view_pubkey);
        bytes
    }

    /// Deserialize from bytes
    pub fn from_bytes(bytes: &[u8; 64]) -> Self {
        let mut spend_pubkey = [0u8; 32];
        let mut view_pubkey = [0u8; 32];
        spend_pubkey.copy_from_slice(&bytes[..32]);
        view_pubkey.copy_from_slice(&bytes[32..]);
        Self {
            spend_pubkey,
            view_pubkey,
        }
    }
}

impl StealthKeyPair {
    /// Generate new random stealth keypair
    #[cfg(feature = "std")]
    pub fn generate<R: RngCore + CryptoRng>(rng: &mut R) -> Self {
        // Generate spend key
        let spend_scalar = Scalar::random(rng);
        let spend_point = Point::basepoint().mul(&spend_scalar);
        
        // Generate view key
        let view_scalar = Scalar::random(rng);
        let view_point = Point::basepoint().mul(&view_scalar);
        
        Self {
            spend_secret: spend_scalar.to_bytes(),
            spend_pubkey: spend_point.to_bytes(),
            view_secret: view_scalar.to_bytes(),
            view_pubkey: view_point.to_bytes(),
        }
    }

    /// Get the public meta address (safe to publish)
    pub fn meta_address(&self) -> StealthMetaAddress {
        StealthMetaAddress {
            spend_pubkey: self.spend_pubkey,
            view_pubkey: self.view_pubkey,
        }
    }
}

// ============================================================================
// Core Functions
// ============================================================================

/// Generate a one-time stealth address for a receiver
/// 
/// # Arguments
/// * `meta_address` - Receiver's published stealth meta address (A, B)
/// * `rng` - Cryptographically secure random number generator
///
/// # Returns
/// * `StealthAddressOutput` containing:
///   - `stealth_pubkey`: The one-time destination address
///   - `ephemeral_pubkey`: R value to publish (receiver needs this to scan)
///
/// # Algorithm
/// 1. Generate random scalar r
/// 2. Compute R = r*G (ephemeral pubkey)
/// 3. Compute shared_secret = r*B (ECDH with view key)
/// 4. Compute stealth_scalar = hash(shared_secret)
/// 5. Compute stealth_pubkey = A + stealth_scalar*G
#[cfg(feature = "std")]
pub fn generate_stealth_address<R: RngCore + CryptoRng>(
    meta_address: &StealthMetaAddress,
    rng: &mut R,
) -> CryptoResult<StealthAddressOutput> {
    // Parse receiver's public keys
    let spend_pubkey_a = Point::from_bytes(&meta_address.spend_pubkey)?;
    let view_pubkey_b = Point::from_bytes(&meta_address.view_pubkey)?;
    
    // Generate random ephemeral scalar r
    let r = Scalar::random(rng);
    
    // R = r*G (ephemeral public key)
    let ephemeral_pubkey_r = Point::basepoint().mul(&r);
    
    // shared_secret = r*B (ECDH)
    let shared_secret_point = view_pubkey_b.mul(&r);
    
    // Hash shared secret to scalar
    let shared_secret_bytes = compute_shared_secret_hash(&shared_secret_point);
    let stealth_scalar = Scalar::from_bytes_mod_order(&shared_secret_bytes);
    
    // stealth_pubkey = A + stealth_scalar*G
    let stealth_offset = Point::basepoint().mul(&stealth_scalar);
    let stealth_pubkey = spend_pubkey_a.add(&stealth_offset);
    
    Ok(StealthAddressOutput {
        stealth_pubkey: stealth_pubkey.to_bytes(),
        ephemeral_pubkey: ephemeral_pubkey_r.to_bytes(),
    })
}

/// Check if a stealth address belongs to you (receiver scanning)
///
/// # Arguments
/// * `view_secret` - Receiver's view secret key (b)
/// * `spend_pubkey` - Receiver's spend public key (A)
/// * `ephemeral_pubkey` - Sender's published R value
/// * `stealth_pubkey` - The stealth address to check
///
/// # Returns
/// * `true` if this stealth address belongs to the receiver
///
/// # Algorithm
/// 1. Compute shared_secret = b*R (ECDH with ephemeral key)
/// 2. Compute expected_stealth = A + hash(shared_secret)*G
/// 3. Return expected_stealth == stealth_pubkey
pub fn check_stealth_address(
    view_secret: &[u8; SCALAR_SIZE],
    spend_pubkey: &[u8; POINT_SIZE],
    ephemeral_pubkey: &[u8; POINT_SIZE],
    stealth_pubkey: &[u8; POINT_SIZE],
) -> CryptoResult<bool> {
    // Parse inputs
    let view_scalar_b = Scalar::from_bytes_mod_order(view_secret);
    let spend_pubkey_a = Point::from_bytes(spend_pubkey)?;
    let ephemeral_r = Point::from_bytes(ephemeral_pubkey)?;
    let target_stealth = Point::from_bytes(stealth_pubkey)?;
    
    // shared_secret = b*R (same as r*B due to ECDH)
    let shared_secret_point = ephemeral_r.mul(&view_scalar_b);
    
    // Hash shared secret
    let shared_secret_bytes = compute_shared_secret_hash(&shared_secret_point);
    let stealth_scalar = Scalar::from_bytes_mod_order(&shared_secret_bytes);
    
    // expected_stealth = A + stealth_scalar*G
    let stealth_offset = Point::basepoint().mul(&stealth_scalar);
    let expected_stealth = spend_pubkey_a.add(&stealth_offset);
    
    // Compare
    Ok(expected_stealth == target_stealth)
}

/// Derive the private key for a stealth address (receiver spending)
///
/// # Arguments
/// * `spend_secret` - Receiver's spend secret key (a)
/// * `view_secret` - Receiver's view secret key (b)
/// * `ephemeral_pubkey` - Sender's published R value
///
/// # Returns
/// * The private key that can spend from the stealth address
///
/// # Algorithm
/// 1. Compute shared_secret = b*R
/// 2. Compute stealth_privkey = a + hash(shared_secret)
pub fn derive_stealth_private_key(
    spend_secret: &[u8; SCALAR_SIZE],
    view_secret: &[u8; SCALAR_SIZE],
    ephemeral_pubkey: &[u8; POINT_SIZE],
) -> CryptoResult<[u8; SCALAR_SIZE]> {
    // Parse inputs
    let spend_scalar_a = Scalar::from_bytes_mod_order(spend_secret);
    let view_scalar_b = Scalar::from_bytes_mod_order(view_secret);
    let ephemeral_r = Point::from_bytes(ephemeral_pubkey)?;
    
    // shared_secret = b*R
    let shared_secret_point = ephemeral_r.mul(&view_scalar_b);
    
    // Hash shared secret
    let shared_secret_bytes = compute_shared_secret_hash(&shared_secret_point);
    let stealth_scalar = Scalar::from_bytes_mod_order(&shared_secret_bytes);
    
    // stealth_privkey = a + stealth_scalar
    let stealth_privkey = spend_scalar_a.add(&stealth_scalar);
    
    Ok(stealth_privkey.to_bytes())
}

/// Derive the stealth public key (for verification)
/// Same computation as generate, but deterministic given R
pub fn derive_stealth_pubkey(
    spend_pubkey: &[u8; POINT_SIZE],
    view_secret: &[u8; SCALAR_SIZE],
    ephemeral_pubkey: &[u8; POINT_SIZE],
) -> CryptoResult<[u8; POINT_SIZE]> {
    // Parse inputs
    let spend_pubkey_a = Point::from_bytes(spend_pubkey)?;
    let view_scalar_b = Scalar::from_bytes_mod_order(view_secret);
    let ephemeral_r = Point::from_bytes(ephemeral_pubkey)?;
    
    // shared_secret = b*R
    let shared_secret_point = ephemeral_r.mul(&view_scalar_b);
    
    // Hash shared secret
    let shared_secret_bytes = compute_shared_secret_hash(&shared_secret_point);
    let stealth_scalar = Scalar::from_bytes_mod_order(&shared_secret_bytes);
    
    // stealth_pubkey = A + stealth_scalar*G
    let stealth_offset = Point::basepoint().mul(&stealth_scalar);
    let stealth_pubkey = spend_pubkey_a.add(&stealth_offset);
    
    Ok(stealth_pubkey.to_bytes())
}

// ============================================================================
// Helper Functions
// ============================================================================

/// Compute hash of shared secret point for stealth derivation
fn compute_shared_secret_hash(shared_secret_point: &Point) -> [u8; SCALAR_SIZE] {
    use sha2::{Sha512, Digest};
    
    let mut hasher = Sha512::new();
    hasher.update(DOMAIN_STEALTH_SHARED_SECRET);
    hasher.update(&shared_secret_point.to_bytes());
    let result = hasher.finalize();
    
    let mut output = [0u8; 32];
    output.copy_from_slice(&result[..32]);
    output
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use rand::rngs::OsRng;

    #[test]
    fn test_stealth_address_roundtrip() {
        let mut rng = OsRng;
        
        // Receiver generates keypair
        let receiver_keys = StealthKeyPair::generate(&mut rng);
        let meta_address = receiver_keys.meta_address();
        
        // Sender generates stealth address
        let stealth_output = generate_stealth_address(&meta_address, &mut rng).unwrap();
        
        // Receiver scans and finds the stealth address
        let is_mine = check_stealth_address(
            &receiver_keys.view_secret,
            &receiver_keys.spend_pubkey,
            &stealth_output.ephemeral_pubkey,
            &stealth_output.stealth_pubkey,
        ).unwrap();
        
        assert!(is_mine, "Receiver should detect their stealth address");
    }

    #[test]
    fn test_stealth_private_key_derivation() {
        let mut rng = OsRng;
        
        // Receiver generates keypair
        let receiver_keys = StealthKeyPair::generate(&mut rng);
        let meta_address = receiver_keys.meta_address();
        
        // Sender generates stealth address
        let stealth_output = generate_stealth_address(&meta_address, &mut rng).unwrap();
        
        // Receiver derives private key
        let stealth_privkey = derive_stealth_private_key(
            &receiver_keys.spend_secret,
            &receiver_keys.view_secret,
            &stealth_output.ephemeral_pubkey,
        ).unwrap();
        
        // Verify: stealth_privkey * G should equal stealth_pubkey
        let derived_scalar = Scalar::from_bytes_mod_order(&stealth_privkey);
        let derived_pubkey = Point::basepoint().mul(&derived_scalar);
        
        assert_eq!(
            derived_pubkey.to_bytes(),
            stealth_output.stealth_pubkey,
            "Derived private key should correspond to stealth public key"
        );
    }

    #[test]
    fn test_different_receivers_get_different_addresses() {
        let mut rng = OsRng;
        
        // Two different receivers
        let receiver1 = StealthKeyPair::generate(&mut rng);
        let receiver2 = StealthKeyPair::generate(&mut rng);
        
        // Generate stealth addresses for each
        let stealth1 = generate_stealth_address(&receiver1.meta_address(), &mut rng).unwrap();
        let stealth2 = generate_stealth_address(&receiver2.meta_address(), &mut rng).unwrap();
        
        // Stealth addresses should be different
        assert_ne!(
            stealth1.stealth_pubkey,
            stealth2.stealth_pubkey,
            "Different receivers should get different stealth addresses"
        );
    }

    #[test]
    fn test_same_receiver_gets_different_addresses() {
        let mut rng = OsRng;
        
        // Same receiver
        let receiver = StealthKeyPair::generate(&mut rng);
        
        // Generate two stealth addresses for same receiver
        let stealth1 = generate_stealth_address(&receiver.meta_address(), &mut rng).unwrap();
        let stealth2 = generate_stealth_address(&receiver.meta_address(), &mut rng).unwrap();
        
        // Each stealth address should be unique (different ephemeral keys)
        assert_ne!(
            stealth1.stealth_pubkey,
            stealth2.stealth_pubkey,
            "Same receiver should get different stealth addresses each time"
        );
        
        // But receiver should be able to detect both
        assert!(check_stealth_address(
            &receiver.view_secret,
            &receiver.spend_pubkey,
            &stealth1.ephemeral_pubkey,
            &stealth1.stealth_pubkey,
        ).unwrap());
        
        assert!(check_stealth_address(
            &receiver.view_secret,
            &receiver.spend_pubkey,
            &stealth2.ephemeral_pubkey,
            &stealth2.stealth_pubkey,
        ).unwrap());
    }

    #[test]
    fn test_wrong_receiver_cannot_detect() {
        let mut rng = OsRng;
        
        // Intended receiver
        let receiver = StealthKeyPair::generate(&mut rng);
        
        // Wrong receiver (attacker)
        let attacker = StealthKeyPair::generate(&mut rng);
        
        // Generate stealth address for intended receiver
        let stealth_output = generate_stealth_address(&receiver.meta_address(), &mut rng).unwrap();
        
        // Attacker tries to scan
        let attacker_check = check_stealth_address(
            &attacker.view_secret,
            &attacker.spend_pubkey,
            &stealth_output.ephemeral_pubkey,
            &stealth_output.stealth_pubkey,
        ).unwrap();
        
        assert!(!attacker_check, "Wrong receiver should not detect stealth address");
    }

    #[test]
    fn test_meta_address_serialization() {
        let mut rng = OsRng;
        let keypair = StealthKeyPair::generate(&mut rng);
        let meta = keypair.meta_address();
        
        let bytes = meta.to_bytes();
        let restored = StealthMetaAddress::from_bytes(&bytes);
        
        assert_eq!(meta, restored, "Meta address should survive serialization roundtrip");
    }
}
